FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Vite React app for production
RUN npm run build

# Install 'serve' to serve the static files
RUN npm install -g serve

# Hugging Face Spaces requires the app to listen on port 7860
EXPOSE 7860

# Serve the 'dist' folder generated by Vite on port 7860
CMD ["serve", "-s", "dist", "-l", "7860"]
